name: build-sea

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Install deps
      run: npm install

  validate-license:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Validate license
      run: |
        npm install
        npm run validate-license

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Run lint
      run: |
        npm install
        npm run lint

  pack:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Run Gulp
      run: |
        npm install
        set NODE_ENV=development&& gulp buildSEA

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Run Mocha tests
      run: |
        npm install
        npm i -g electron-mocha
        electron-mocha src/**/*.spec.js --timeout 5000
